import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Toast } from "@/components/ui/toast"
import { Toaster } from "@/components/ui/toaster"
import AuthContextProvider from "@/context/useAuth"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <AuthContextProvider>
        <body className={inter.className}>
          <main>{children}</main>
          <Toaster />
        </body>
      </AuthContextProvider>
    </html>
  )
}
